#█████▀█████████████████████████████████████████████
#█─▄▄▄▄█▄─▄▄▀█▄─▄▄─██▀▄─██─▄─▄─███─▄─▄─██▀▄─██▄─▄─▀█
#█─██▄─██─▄─▄██─▄█▀██─▀─████─███████─████─▀─███─▄─▀█
#▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀▀▄▄▄▀▀▀▀▀▄▄▄▀▀▄▄▀▄▄▀▄▄▄▄▀▀

prefix: "&b&lGreatTab &8» &7"